###############################################################################
# Tekton Pipeline using CEL in WhenExpressions
###############################################################################
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-image-cel
  namespace: planton-cloud-pipelines
spec:
  params:
    - name: git-url
      type: string
      description: "The Git URL to clone"

    - name: git-revision
      type: string
      description: "Git revision to checkout"
      default: "main"

    - name: image-name
      type: string
      description: "The final image name to be built/pushed"

    - name: pipeline-id
      type: string
      description: "id of the pipeline on planton-cloud"

  workspaces:
    - name: source
      description: "Workspace that stores source code & build artifacts"

  tasks:
    #################################################################
    # 1) GIT-CHECKOUT
    #################################################################
    - name: git-checkout
      taskRef:
        resolver: hub
        params:
          - name: type
            value: tekton
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.9"
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: source

    #################################################################
    # 2) BUILD-IMAGE (with Buildpacks) - Optional Example
    #################################################################
    - name: build-image
      runAfter:
        - git-checkout
      taskRef:
        resolver: hub
        params:
          - name: type
            value: tekton
          - name: kind
            value: task
          - name: name
            value: buildpacks
          - name: version
            value: "0.6"
      params:
        - name: BUILDER_IMAGE
          #https://cloud.google.com/docs/buildpacks/builders
          value: "gcr.io/buildpacks/builder:google-22"
        - name: PROCESS_TYPE
          value: ""
        - name: PATH
          value: "."
        - name: APP_IMAGE
          value: "$(params.image-name)"
        - name: PUSH_IMAGE
          value: "false"
      workspaces:
        - name: source
          workspace: source

    #################################################################
    # 3) KUSTOMIZE BUILD
    #################################################################
    - name: kustomize-build
      runAfter:
        - git-checkout
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/plantoncloud/tekton-hub.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/kustomize-build.yaml"
      workspaces:
        - name: source
          workspace: source
      params:
        - name: configMapName
          value: "$(params.pipeline-id)"
        - name: configMapNamespace
          value: "planton-cloud-pipelines"
