apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-upload-cloudflare-worker
  namespace: planton-cloud-pipelines
spec:
  description: >
    A Pipeline to build a Cloudflare Worker bundle and upload it to R2 storage.
  params:
    - name: git-url
      type: string
      description: "The Git URL to clone"
    - name: git-revision
      type: string
      description: "Git revision to checkout"
      default: "main"
    - name: git-branch
      type: string
      description: "Git branch name"
      default: ""
    - name: project-root
      type: string
      description: "Relative path to the project's root inside the cloned repo"
      default: "."
    - name: package-manager-directory
      type: string
      description: "Directory to run package manager install from (defaults to project-root, set to '.' for monorepo workspaces)"
      default: ""
    - name: sparse-checkout-directories
      type: string
      description: "list of comma separated directory patterns to git-clone Task's sparseCheckoutDirectories param"
      default: ""
    - name: r2-bucket-name
      type: string
      description: "Name of the R2 bucket to upload worker bundle"
    - name: r2-endpoint-url
      type: string
      description: "R2 S3-compatible endpoint URL"
    - name: r2-object-key
      type: string
      description: "Object key/path in R2 bucket (e.g., service-name/commit-sha.js)"
    - name: worker-script-artifact-config-map-name
      type: string
      description: "Name of the config-map to store worker script artifact metadata"
    - name: kustomize-manifests-config-map-name
      type: string
      description: "Name of the config-map to store service manifests generated by kustomize"
    - name: kustomize-base-directory
      type: string
      description: "Relative path to the kustomize base directory inside project root"
      default: "_kustomize"
    - name: owner-identifier-label-key
      type: string
      description: Optional owner identifier label key to add to the ConfigMap
      default: ""
    - name: owner-identifier-label-value
      type: string
      description: Optional owner identifier label value
      default: ""

  workspaces:
    - name: source
      description: "Workspace where source code is cloned"
    - name: r2-credentials
      description: "Workspace containing R2 access credentials"

  tasks:
    ########################################################################
    # 1) Clone source from Git
    ########################################################################
    - name: git-checkout
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/plantonhq/tekton-hub.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/git-clone.yaml"
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
        - name: deleteExisting
          value: "true"
        - name: sparseCheckoutDirectories
          value: "$(params.sparse-checkout-directories)"
        - name: gitInitImage
          value: "ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/git-init:v0.45.0"
      workspaces:
        - name: output
          workspace: source

    ########################################################################
    # 2) Install dependencies (npm/yarn/pnpm auto-detection)
    ########################################################################
    - name: install-dependencies
      runAfter:
        - git-checkout
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: project-root
          - name: package-manager-directory
        steps:
          - name: install
            image: node:20-alpine
            workingDir: /workspace/source
            script: |
              #!/bin/sh
              set -e
              
              # Determine install directory (defaults to project-root if not specified)
              INSTALL_DIR="$(params.package-manager-directory)"
              if [ -z "$INSTALL_DIR" ]; then
                INSTALL_DIR="$(params.project-root)"
              fi
              
              cd "$INSTALL_DIR"
              echo "Installing dependencies in: $INSTALL_DIR"
              
              echo "Detecting package manager..."
              
              if [ -f "yarn.lock" ]; then
                echo "Found yarn.lock - using Yarn"
                corepack enable
                yarn install --frozen-lockfile
              elif [ -f "pnpm-lock.yaml" ]; then
                echo "Found pnpm-lock.yaml - using pnpm"
                npm install -g pnpm
                pnpm install --frozen-lockfile
              elif [ -f "package-lock.json" ]; then
                echo "Found package-lock.json - using npm"
                npm ci
              elif [ -f "package.json" ]; then
                echo "Found package.json - using npm install"
                npm install
              else
                echo "No package.json found - skipping dependency installation"
              fi
      params:
        - name: project-root
          value: "$(params.project-root)"
        - name: package-manager-directory
          value: "$(params.package-manager-directory)"
      workspaces:
        - name: source

    ########################################################################
    # 3) Bundle Worker with wrangler
    ########################################################################
    - name: bundle-worker
      runAfter:
        - install-dependencies
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: project-root
        results:
          - name: bundle-hash
            description: "SHA256 hash of bundled script"
          - name: bundle-size
            description: "Bundle size in bytes"
        steps:
          - name: bundle
            image: node:20-alpine
            workingDir: /workspace/source
            script: |
              #!/bin/sh
              set -e
              
              PROJECT_ROOT="$(params.project-root)"
              
              echo "Bundling Cloudflare Worker..."
              echo "Project root: $PROJECT_ROOT"
              
              # Check if wrangler.toml exists at project root
              if [ ! -f "$PROJECT_ROOT/wrangler.toml" ]; then
                echo "ERROR: wrangler.toml not found at $PROJECT_ROOT/wrangler.toml"
                exit 1
              fi
              
              # Bundle the worker from repo root with --config pointing to project's wrangler.toml
              # This allows esbuild to resolve workspace dependencies from node_modules at repo root
              # Note: --outdir is relative to wrangler.toml location, so use "dist" not "$PROJECT_ROOT/dist"
              npx wrangler deploy --dry-run \
                --config "$PROJECT_ROOT/wrangler.toml" \
                --outdir dist
              
              # Verify bundle was created
              if [ ! -f "$PROJECT_ROOT/dist/index.js" ]; then
                echo "ERROR: Bundle not created at $PROJECT_ROOT/dist/index.js"
                exit 1
              fi
              
              echo "Bundle created successfully"
              
              # Calculate SHA256 hash
              HASH=$(sha256sum "$PROJECT_ROOT/dist/index.js" | cut -d' ' -f1)
              echo -n "$HASH" > $(results.bundle-hash.path)
              echo "Bundle hash: $HASH"
              
              # Get bundle size in bytes
              SIZE=$(stat -c%s "$PROJECT_ROOT/dist/index.js" 2>/dev/null || stat -f%z "$PROJECT_ROOT/dist/index.js")
              echo -n "$SIZE" > $(results.bundle-size.path)
              echo "Bundle size: $SIZE bytes"
              
              # Show bundle info
              ls -lh "$PROJECT_ROOT/dist/index.js"
      params:
        - name: project-root
          value: "$(params.project-root)"
      workspaces:
        - name: source

    ########################################################################
    # 4) Upload bundle to R2
    ########################################################################
    - name: upload-to-r2
      runAfter:
        - bundle-worker
      taskSpec:
        workspaces:
          - name: source
          - name: r2-credentials
        params:
          - name: project-root
          - name: r2-bucket-name
          - name: r2-endpoint-url
          - name: r2-object-key
        results:
          - name: artifact-url
            description: "Full R2 URL to the uploaded bundle"
        steps:
          - name: upload
            image: amazon/aws-cli:latest
            workingDir: /workspace/source
            script: |
              #!/bin/bash
              set -e
              
              PROJECT_ROOT="$(params.project-root)"
              
              # Read R2 credentials from workspace mount
              export AWS_ACCESS_KEY_ID=$(cat /workspace/r2-credentials/access-key-id)
              export AWS_SECRET_ACCESS_KEY=$(cat /workspace/r2-credentials/secret-access-key)
              
              echo "Uploading worker bundle to R2..."
              echo "Project root: $PROJECT_ROOT"
              echo "Bucket: $(params.r2-bucket-name)"
              echo "Key: $(params.r2-object-key)"
              
              # Upload to R2 using S3-compatible API
              aws s3 cp \
                "$PROJECT_ROOT/dist/index.js" \
                s3://$(params.r2-bucket-name)/$(params.r2-object-key) \
                --endpoint-url $(params.r2-endpoint-url)
              
              echo "Upload successful!"
              
              # Construct artifact URL
              ARTIFACT_URL="$(params.r2-endpoint-url)/$(params.r2-bucket-name)/$(params.r2-object-key)"
              echo -n "$ARTIFACT_URL" > $(results.artifact-url.path)
              echo "Artifact URL: $ARTIFACT_URL"
      params:
        - name: project-root
          value: "$(params.project-root)"
        - name: r2-bucket-name
          value: "$(params.r2-bucket-name)"
        - name: r2-endpoint-url
          value: "$(params.r2-endpoint-url)"
        - name: r2-object-key
          value: "$(params.r2-object-key)"
      workspaces:
        - name: source
        - name: r2-credentials

    ########################################################################
    # 5) Store artifact metadata in ConfigMap
    ########################################################################
    - name: store-artifact-metadata
      runAfter:
        - upload-to-r2
      taskSpec:
        params:
          - name: config-map-name
          - name: config-map-namespace
          - name: r2-bucket-name
          - name: r2-object-key
          - name: bundle-hash
          - name: bundle-size
          - name: owner-identifier-label-key
          - name: owner-identifier-label-value
        steps:
          - name: create-configmap
            image: bitnami/kubectl:latest
            script: |
              #!/bin/bash
              set -e
              
              echo "Creating ConfigMap with artifact metadata..."
              
              # Create or update ConfigMap
              kubectl create configmap $(params.config-map-name) \
                --from-literal=bucket=$(params.r2-bucket-name) \
                --from-literal=path=$(params.r2-object-key) \
                --from-literal=content-hash=$(params.bundle-hash) \
                --from-literal=size-bytes=$(params.bundle-size) \
                --namespace=$(params.config-map-namespace) \
                --dry-run=client -o yaml | kubectl apply -f -
              
              # Apply base label
              kubectl label configmap $(params.config-map-name) \
                --namespace=$(params.config-map-namespace) \
                app.kubernetes.io/managed-by=planton-cloud \
                --overwrite
              
              # Apply owner identifier label if provided
              if [ -n "$(params.owner-identifier-label-key)" ] && [ -n "$(params.owner-identifier-label-value)" ]; then
                kubectl label configmap $(params.config-map-name) \
                  --namespace=$(params.config-map-namespace) \
                  $(params.owner-identifier-label-key)=$(params.owner-identifier-label-value) \
                  --overwrite
              fi
              
              echo "ConfigMap $(params.config-map-name) created/updated successfully"
      params:
        - name: config-map-name
          value: "$(params.worker-script-artifact-config-map-name)"
        - name: config-map-namespace
          value: "planton-cloud-pipelines"
        - name: r2-bucket-name
          value: "$(params.r2-bucket-name)"
        - name: r2-object-key
          value: "$(params.r2-object-key)"
        - name: bundle-hash
          value: "$(tasks.bundle-worker.results.bundle-hash)"
        - name: bundle-size
          value: "$(tasks.bundle-worker.results.bundle-size)"
        - name: owner-identifier-label-key
          value: "$(params.owner-identifier-label-key)"
        - name: owner-identifier-label-value
          value: "$(params.owner-identifier-label-value)"

    ########################################################################
    # 6) Kustomize build
    ########################################################################
    - name: kustomize-build
      runAfter:
        - git-checkout
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/plantonhq/tekton-hub.git"
          - name: revision
            value: "main"
          - name: pathInRepo
            value: "tasks/kustomize-build.yaml"
      params:
        - name: config-map-name
          value: "$(params.kustomize-manifests-config-map-name)"
        - name: config-map-namespace
          value: "planton-cloud-pipelines"
        - name: project-root
          value: "$(params.project-root)"
        - name: kustomize-base-directory
          value: "$(params.kustomize-base-directory)"
        - name: owner-identifier-label-key
          value: "$(params.owner-identifier-label-key)"
        - name: owner-identifier-label-value
          value: "$(params.owner-identifier-label-value)"
      workspaces:
        - name: source
          workspace: source

